export const projects = [
  {
    id: 'araaz',
    name: 'Araaz E-commerce Website',
    subtitle: 'A modern and responsive e-commerce platform.',
    desc: 'Developed a fully responsive e-commerce website with automated contact handling using Web3Forms and deployment on Vercel.',
    tech: ['HTML', 'CSS', 'JavaScript', 'Web3Forms', 'Vercel'],
    features: ['Fully Responsive Design', 'Automated Contact Handling (Web3Forms)', 'Clean and Modern UI/UX', 'Deployed on Vercel', 'Optimized for Performance'],
    live: 'https://araaaz.vercel.app/',
    github: 'https://github.com/nimrawani04',
    color: '#a855f7',
    status: 'COMPLETED',
    levelRequired: 1,
    story: 'This was my first real-world e-commerce system. I built a complete flow from UI to deployment.',
    challenges: ['Making layout responsive across devices', 'Handling contact automation without backend', 'Optimizing load times for product images'],
    learned: ['Production-ready UI design', 'Deployment workflows (Vercel)', 'Form handling with Web3Forms'],
    approach: ['Used Web3Forms to avoid backend complexity', 'Focused on performance-first design', 'Prioritized mobile responsiveness'],
    optimizations: ['Lazy loading images', 'Clean CSS structure', 'Fast deployment via Vercel'],
    systemFlow: 'User → Browse Products → Add to Cart → Contact Form → Web3Forms → Email Sent',
    skillsGained: ['Responsive Design', 'API Integration', 'Deployment'],
    missionObj: ['Product browsing', 'Contact automation', 'Deployment pipeline']
  },
  {
    id: 'academic-portal',
    name: 'Academic Portal System – CUK',
    subtitle: 'Full-stack academic portal for students and faculty.',
    desc: 'Designed and developed a full-stack academic portal featuring role-based authentication, personalized dashboards, attendance tracking, marks management, notices, and exam-related workflows.',
    tech: ['React', 'TypeScript', 'Supabase', 'PostgreSQL', 'Vercel'],
    features: ['Role-based Authentication', 'Personalized Dashboards', 'Attendance Tracking', 'Marks Management', 'Exam Workflows'],
    live: '',
    github: 'https://github.com/nimrawani04',
    color: '#4ade80',
    status: 'COMPLETED',
    levelRequired: 1,
    story: 'A university-scale portal that handles everything from attendance to exams. My biggest full-stack challenge.',
    challenges: ['Implementing role-based access for students/faculty', 'Real-time data sync with Supabase', 'Complex dashboard state management'],
    learned: ['Full-stack architecture patterns', 'Database design with PostgreSQL', 'TypeScript for large-scale apps'],
    approach: ['Used Supabase for backend-as-a-service', 'TypeScript for type safety', 'Component-driven architecture'],
    optimizations: ['Efficient query patterns', 'Lazy-loaded dashboard modules', 'Cached auth sessions'],
    systemFlow: 'Login → Role Detection → Dashboard → Attendance/Marks/Notices → Admin Panel',
    skillsGained: ['Full-Stack Dev', 'Database Design', 'Auth Systems'],
    missionObj: ['Role-based auth', 'Dashboard system', 'Data management']
  },
  {
    id: 'bis-ai',
    name: 'BIS AI – Product Safety Assistant',
    subtitle: 'AI-powered product verification platform.',
    desc: 'Built an AI-powered product verification platform inspired by BIS standards, enabling users to check product authenticity and compliance with Indian regulations.',
    tech: ['React', 'TypeScript', 'Supabase', 'PostgreSQL', 'PWA', 'Vercel'],
    features: ['AI Chatbot', 'Multilingual Support', 'Product Verification', 'Real-time Guidance', 'PWA Interface'],
    live: 'https://bis-ai.vercel.app/',
    github: 'https://github.com/nimrawani04',
    color: '#3b82f6',
    status: 'COMPLETED',
    levelRequired: 2,
    story: 'An AI-powered assistant that helps users verify product safety against Indian BIS standards. Built for a hackathon.',
    challenges: ['Implementing RAG pipeline', 'Multilingual NLP support', 'Offline-first PWA architecture'],
    learned: ['AI/ML integration in web apps', 'RAG pipeline architecture', 'PWA development'],
    approach: ['RAG for context-aware responses', 'PWA for offline access', 'Supabase for vector storage'],
    optimizations: ['Service worker caching', 'Chunked AI responses', 'Optimized vector queries'],
    systemFlow: 'User Query → AI Processing → RAG Retrieval → Verification → Response',
    skillsGained: ['AI Integration', 'RAG Pipelines', 'PWA Dev'],
    missionObj: ['AI chatbot', 'Product verification', 'Multilingual support']
  },
  {
    id: 'rasta-ai',
    name: 'Rasta AI – Smart Assistance Platform',
    subtitle: 'Multi-domain AI assistance platform.',
    desc: 'Developed an AI platform structured across four domains—document understanding, crop intelligence, youth services, and AI-guided support.',
    tech: ['React', 'TypeScript', 'Supabase', 'PostgreSQL', 'Vercel'],
    features: ['Voice/Text Interaction', 'Multilingual Support', 'Document Understanding', 'Crop Intelligence', 'Career Assistance'],
    live: 'https://cursor-hackathon-roan.vercel.app/',
    github: 'https://github.com/nimrawani04',
    color: '#10b981',
    status: 'COMPLETED',
    levelRequired: 2,
    story: 'A multi-domain AI platform that won 2nd place at the Cursor Kashmir Hackathon. Four AI modules in one app.',
    challenges: ['Multi-domain AI architecture', 'Voice interaction integration', 'Real-time crop analysis'],
    learned: ['AI platform architecture', 'Voice/Text multimodal input', 'Hackathon rapid development'],
    approach: ['Domain-specific AI modules', 'Shared inference pipeline', 'Progressive feature loading'],
    optimizations: ['Lazy-loaded AI modules', 'Streaming responses', 'Cached domain models'],
    systemFlow: 'Select Domain → Input (Voice/Text) → AI Processing → Domain Response → Action',
    skillsGained: ['AI Architecture', 'Voice AI', 'Rapid Prototyping'],
    missionObj: ['Multi-domain AI', 'Voice interaction', 'Hackathon delivery']
  },
  {
    id: '2ai-conference',
    name: '2AI Conference Website',
    subtitle: '2026 International Conference on Applied AI.',
    desc: 'Collaborated on the design and development of the official conference website, focusing on crafting a clean, modern UI/UX and implementing a responsive, user-friendly frontend.',
    tech: ['JavaScript', 'TypeScript', 'CSS', 'HTML'],
    features: ['Clean Modern UI/UX', 'Responsive Design', 'Accessible Content', 'Seamless Navigation', 'Global Audience Ready'],
    live: 'https://2ai-conference.org/',
    github: 'https://github.com/nimrawani04',
    color: '#22d3ee',
    status: 'COMPLETED',
    levelRequired: 3,
    story: 'Built the official website for an international AI conference. Focused on clean design for a global audience.',
    challenges: ['Designing for academic audience expectations', 'Ensuring cross-browser compatibility', 'Meeting tight conference deadlines'],
    learned: ['Professional client collaboration', 'Accessibility best practices', 'SEO for event websites'],
    approach: ['Mobile-first responsive design', 'Semantic HTML for accessibility', 'Performance-optimized assets'],
    optimizations: ['Minified assets', 'Optimized images', 'Clean semantic markup'],
    systemFlow: 'Landing → About → Speakers → Schedule → Registration → Contact',
    skillsGained: ['UI/UX Design', 'Accessibility', 'Client Work'],
    missionObj: ['Professional UI', 'Responsive layout', 'Global accessibility']
  },
  {
    id: 'exam-system',
    name: 'CUK Examination Management System',
    subtitle: 'Secure exam management with role-based access.',
    desc: 'Collaboratively developed a secure and scalable examination management system with role-based access control and real-time data handling.',
    tech: ['React', 'TypeScript', 'Supabase', 'PostgreSQL', 'Vercel'],
    features: ['Role-based Access Control', 'Real-time Data Handling', 'Authentication Workflows', 'Responsive UI', 'Exam Scheduling'],
    live: 'https://secure-exam-flow.vercel.app/',
    github: 'https://github.com/nimrawani04',
    color: '#f59e0b',
    status: 'IN PROGRESS',
    levelRequired: 4,
    story: 'A secure system for managing university examinations with strict access control and real-time updates.',
    challenges: ['Building secure auth workflows', 'Handling concurrent exam data', 'Complex scheduling logic'],
    learned: ['Security-first development', 'Real-time data patterns', 'Complex state management'],
    approach: ['Row-level security in Supabase', 'Optimistic UI updates', 'Component isolation for security'],
    optimizations: ['Debounced API calls', 'Cached exam schedules', 'Efficient re-renders'],
    systemFlow: 'Auth → Role Check → Exam Dashboard → Schedule/Create → Monitor → Results',
    skillsGained: ['Security', 'Real-time Data', 'Exam Systems'],
    missionObj: ['Secure access', 'Exam scheduling', 'Result management']
  },
  {
    id: 'acadex',
    name: 'CUK Acadex',
    subtitle: 'University-wide academic portal.',
    desc: 'Contributed to the development of a university-wide academic portal by building student and teacher portals with role-based dashboards.',
    tech: ['React', 'TypeScript', 'Supabase', 'PostgreSQL', 'Vercel'],
    features: ['Student & Teacher Portals', 'Role-based Dashboards', 'Attendance Access', 'Marks & Notices', 'Responsive UI'],
    live: 'https://ds-cuk.vercel.app/',
    github: 'https://github.com/nimrawani04',
    color: '#ec4899',
    status: 'LOCKED',
    levelRequired: 5,
    story: 'Built dual portals for students and teachers with seamless data flow between roles.',
    challenges: ['Dual-portal architecture', 'Cross-role data visibility', 'Responsive complex tables'],
    learned: ['Multi-role app architecture', 'Data normalization', 'Collaborative development'],
    approach: ['Shared component library', 'Role-based routing', 'Modular dashboard widgets'],
    optimizations: ['Virtualized lists', 'Paginated data fetching', 'Memoized components'],
    systemFlow: 'Login → Student/Teacher Portal → Dashboard → Attendance/Marks → Notices',
    skillsGained: ['Portal Design', 'Data Flow', 'Team Collaboration'],
    missionObj: ['Student portal', 'Teacher portal', 'Data management']
  },
  {
    id: 'smart-house',
    name: 'Smart House using Arduino',
    subtitle: 'IoT-based home automation prototype.',
    desc: 'Designed an IoT-based home automation prototype integrating multiple sensors for intelligent environmental control.',
    tech: ['Arduino', 'C++', 'Infrared Sensors', 'Ultrasonic Sensors'],
    features: ['Sensor Integration', 'Environmental Control', 'Automated Responses', 'IoT Architecture', 'Prototype Design'],
    live: '',
    github: 'https://github.com/nimrawani04',
    color: '#f97316',
    status: 'LOCKED',
    levelRequired: 6,
    story: 'My first hardware project — bridging software and physical computing. A fully automated smart house prototype.',
    challenges: ['Hardware-software integration', 'Sensor calibration and noise', 'Power management for sensors'],
    learned: ['Embedded systems programming', 'Sensor data processing', 'Hardware prototyping'],
    approach: ['Modular sensor architecture', 'Interrupt-driven design', 'Iterative hardware testing'],
    optimizations: ['Efficient power cycling', 'Debounced sensor reads', 'Optimized C++ for Arduino'],
    systemFlow: 'Sensors → Arduino → Logic Processing → Actuators → Environmental Control',
    skillsGained: ['IoT', 'Embedded Systems', 'Hardware Design'],
    missionObj: ['Sensor integration', 'Automated control', 'Prototype design']
  }
];

export const achievements = [
  { title: '1st Position – Logo Designing', desc: 'Cyber Conclave 2025, Central University of Kashmir. Recognized for creativity, visual communication, and design thinking.' },
  { title: '1st Position – Open Build Challenge', desc: 'FOSS NIT Srinagar in collaboration with FOSS United. Demonstrated strong problem-solving skills and collaborative development.' },
  { title: '2nd Position – Cursor Kashmir Hackathon', desc: 'Built Rasta AI, an AI platform for document simplification, crop insights, youth services, and AI-guided assistance.' },
  { title: 'Standard-a-Thon Hackathon', desc: 'FOSS Club, NIT Srinagar. Developed BIS AI, an AI-powered assistant with RAG pipeline, multilingual support, and offline accessibility.' },
  { title: 'Coding Challenge – Tech Summit 2025', desc: 'Competitive coding event focused on problem-solving, logical reasoning, and teamwork.' },
  { title: 'Code Debugging – Cyber Conclave 2025', desc: 'Solved debugging challenges in C, emphasizing analytical thinking and error resolution.' },
  { title: 'Treasure Hunt – Cyber Conclave 2025', desc: 'Team-based challenge requiring decision-making, time management, and critical thinking.' },
  { title: 'Coding Competition – National Tech Day 2024', desc: 'Competitive coding event focused on problem-solving, debugging, and logical reasoning under time constraints.' }
];

export const certificates = [
  { title: 'Introduction to AI Concepts', org: 'Microsoft', date: 'Jan 2026', skills: 'AI, Generative AI, Responsible AI, Computer Vision', link: 'https://learn.microsoft.com/api/achievements/share/en-gb/NimraWani-9486/WV44L35N?sharingId=B856B6811014E40C' },
  { title: 'Introduction to ML Concepts', org: 'Microsoft', date: 'Jan 2026', skills: 'ML, Linear Regression, Classification, Clustering, Deep Learning', link: 'https://learn.microsoft.com/api/achievements/share/en-gb/NimraWani-9486/KC8WHGGB?sharingId=B856B6811014E40C' },
  { title: 'AI Fundamentals', org: 'IBM SkillsBuild', date: 'Dec 2025', skills: 'AI, ML, Deep Learning, AI Ethics, Computer Vision, NLP', link: 'https://www.credly.com/badges/a36fcbd9-3963-4a4a-b29b-19ff4792aaf1/linked_in_profile' },
  { title: 'OCI 2025 AI Foundations Associate', org: 'Oracle', date: 'Dec 2025', skills: 'AI, ML, Deep Learning, Cloud Computing, OCI', link: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=C982AECE9426EA178736DD1F01312EA6B7ECF089391F6FDDCF9CCBCC6CB1A243' },
  { title: 'Prepare Data for ML APIs', org: 'Google Cloud', date: 'Dec 2025', skills: 'Python, TensorFlow, ML, Dataflow, Cloud NLP API', link: 'https://www.credly.com/badges/0c570f0b-e9e3-4228-962c-c6b06ac28f8c/linked_in_profile' },
  { title: 'DSA in Modern Product Engineering', org: 'TechBairn', date: 'Dec 2025', skills: 'Algorithms, Problem Solving, Data Structures', link: '' },
  { title: 'Python for AI (5-Day Workshop)', org: 'NIT Srinagar', date: 'Nov 2025', skills: 'NumPy, Pandas, Scikit-Learn', link: '' }
];

export const experience = [
  { title: 'Campus Lead', org: 'Open Source Global Connect', period: 'Dec 2025 – Present', desc: 'Led and coordinated open-source awareness initiatives, organized technical sessions, and mentored students in open source contributions.' },
  { title: 'Student Intern', org: 'National Institute of Technology Srinagar', period: 'Dec 2025 – Feb 2026', desc: 'Gaining hands-on experience in applied computer science through coding exercises, problem-solving tasks, and academic mentorship.' },
  { title: 'Mentor', org: 'SWOC (Social Winter of Code)', period: 'Jan 2026 – Mar 2026', desc: 'Mentoring contributors in front-end web development, guiding them through project-based learning and open-source collaboration.' }
];

export const education = [
  { title: 'B.Tech in Computer Science & Engineering', org: 'Central University of Kashmir, Ganderbal', period: 'Expected July 2027' },
  { title: '12th (CBSE) — Medical + Mathematics', org: 'Delhi Public School, Srinagar', period: '2022' }
];
